### ISSUE TITLE
b67 - Debugging Multi-Thread application and double clicking Main Thread doesn't jump to Location from Thread Window

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#144]
Win 7 64 bit
bbndk 10.0.10.261
b 1.0.0014

1.Debug Multi threaded application
2.Hit a breakpoint in the thread
3.Double click on Main Thread from the Thread Window

Behaviour:
a No Source Available Tab opens

**Comment by mattcostanzo** [comment]
guarnold commented 3 months ago 
I cannot reproduce these issue after the latest fixes. Could you verify that?

 evillaricomarbella commented 3 months ago 
reproducible build 84 ver 1.0.0029 - hitting a breakpoint in a worker thread in and double clicking on Locations doesn't jump to location in the code. One has to use the dropdown list and click there.

Clicking Main Thread still open a No Source Available editor

 guarnold commented 2 months ago 
Sometimes the Main Thread has [External Code] as location. That means that the main thread is running external libraries. So, if you double click on the main thread it is correct to show you No Source Available.

It would be a bug if the location has a method name and it opens No Source Available. Could you check this?

Now if you ask me why the GDB command that inquiries the call stack does not return any reference to the main function for the Main Thread I have no idea for now. That is weird and I will have to investigate it later, if it is an issue.

 allee commented 2 months ago 
Lowered to P3

**Comment by guarnold** [comment]
GDB is returning more information about the stack frames. However, some times, the location is [External Code] and that means that it might not jump to the location from the thread window when that happens, opening the No Source Available window.

This issue will be closed because GDB is returning all the information that we need, except sometimes that the program really is running an external code. When that happens, there is nothing to be presented.

**Comment by pvallabhaneni** [comment]
Verified on Win 7 64 bit using 2.0.0022 plugin. Debugged a multi-thread project and hit a break-point. Double clicked on main thread, "No source Available" tab is not opened. Verification Passed.
