### ISSUE TITLE
Open Source Setup Script Missing Files

### ISSUE THREAD

**Issue by dbrgss** [blackberry/VSPlugin#176]
Need to add a few files to the setup script.

**Comment by zadmarbella** [comment]
@dbrgss what is the expected behaviour? we need some docs on how do this.

**Comment by dbrgss** [comment]
The only way to verify this is to use the script and then run a quick smoke test to see that everything is working correctly in visual studio..  You would just need to verify that all the various pieces are there.  To do this I would suggest the following to test each component.

1) GDBParser - Need to debug an application
2) VSNDK.AddIn - Need to debug an application
3) VSNDK.DebugEngine - Need to debug an application
4) VSNDK.Package - Make sure BlackBerry menu is displayed and works
5) VSNDK.Tasks - Need to build an application

**Comment by mattcostanzo** [comment]
Testing needs to be done on this

**Comment by zadmarbella** [comment]
Need more information on what scripts to run and file locations seeing VSNDKPluginBuild.bat and VSNDKPluginSetup.bat

**Comment by mattcostanzo** [comment]
basic smoke test required to verify

**Comment by zadmarbella** [comment]
Prerequisite: 
An installation of the old plugin
Plug-in for Microsoft Visual Studio
https://developer.blackberry.com/native/download/

Note: You can uninstall the Plugin as normal, via the Control Panel, but it will uninstall the entire plugin and not just the version you just "upgraded" to.   

Steps to verify script:
Run the VSNDKPluginBuild.bat to build project
A build results folder outside the git repo is created called buildresults
where all the built files are created.

Turn off Visual Studio and verify that MSBuild is not running in the Task Manager
Failing to do so fails to copy files.

Run the VSNDKPluginSetup.bat to copy the files in the correct locations
if an old installation exists this batch file will overwrite them so the Date Modified will match the 
Date Modified of the files in the buildresults folder.

Then attempt to debug with it.

Feedback:
- The execution steps are fairly simple. 
- VSNDKPluginSetup.bat should output some form of logs so that user is able to verify if the script passed or not.
- Build folders are created outside the repo when they should be inside the repo and be ignored by git.
- Build items in the src folder are added to the repository files that should be ignored 
- The only way to uninstall the plugin is to have an old version of it and regedit artifacts persist ie PortSupplier DebugEngine
- Features that are expected in next do not appear when script installs plugin (we are missing Attach to process and being able to edit Local/Watch/Immediate variables.)
- We need an uninstall script that removes everything using an old version of the plugin is not ideal

Possible issues VSNDKPluginSetup.bar:
This folder doesn't exist and fails to copy
copy "%buildresults%\GDBParser.dll" "%ProgRoot%\Research In Motion\VSPlugin-NDK\GDBParser.dll"
Unclear if this folder is used but at the current state of this script a user is not going to be able to debug as expected.

-[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\10.0\AD7Metrics\PortSupplier{92A2B753-00BD-40FF-9964-6AB64A1D6C9F} ] < has a space could break Attach to Process functionality unable to verify if this is the case cause the feature is missing. Based on the first issue.

**Comment by dbrgss** [comment]
1 VSNDKPluginSetup.bat should output some form of logs so that user is able to verify if the script passed or not.

This can be done by reading the output of the script from the command line window.  A user could also have the output sent to a file through a command line pipe.

2 Build folders are created outside the repo when they should be inside the repo and be ignored by git.

I don't see the benefit of this.  It could be done but what does it serve.

3 Build items in the src folder are added to the repository files that should be ignored

Agreed...  build items should not be part of the repository

4 The only way to uninstall the plugin is to have an old version of it and regedit artifacts persist ie PortSupplier\*  DebugEngine

This is caused by our current necessity of having a previous install of the plugin already installed.   (This requirement comes from the need of certain precompiled NDK files that allow us to do the optimized build.  We cannot distribute these files via open source so we need to have them installed via a scm install).  Having to use regedit to remove the PortSupplier etc.. is caused by the fact that the installer did not install those keys.   You are correct though...  we probably should have an uninstall command line script as well...  

5 Features that are expected in next do not appear when script installs plugin (we are missing Attach to process and being able to edit Local/Watch/Immediate variables.)

This would be caused by the fact that the script was not updated with these new features when they were added to Next.  We will need to make sure that whenever we add a feature that directly affects the files and/or registry keys for the plugin that we make the appropriate changes not only to the installer but to the setup scripts. 

6 We need an uninstall script that removes everything using an old version of the plugin is not ideal

See my response to point 4 above.
