### ISSUE TITLE
Test Attach to Process

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#190]
Possible Issues
#248
#249
#250
#251
#252
#253
#254

**Comment by mattcostanzo** [comment]
Est 1 day

**Comment by guarnold** [comment]
Before start testing attach to process, be sure to chose an app in the device that was build and deployed from the same computer. When the user clicks play button, the source and symbol information about the app are stored in the file ProcessesPaths.txt. Then, when attaching to a running process, the debugger could find the information that it needs to debug the app. If that information is not found in the file, i.e., you are debugging an app that was not deployed from your computer, the debugger will be attached to the process but you will not be able to debug it, because the souce and symbol data could not be found.

1 - Start an app in the device.
2 - Start a new instance of visual studio 
3 - Enter the Device information into BlackBerry settings.
4 - In the menu, chose: Debug -> Attach to Process
5 - In Transport, chose: BlackBerry (you must see a Transport Information below the Qualifier)
6 - In Qualifier, chose: Device. (If you also set the Simulator information into BlackBerry settings, you might see Simulator as an option to attach. Do not use Simulator for now.)
7 - Chose the app to debug in the list of Available Process. If you didn't start the app, do it in the device and then click Refresh button to update this list.
8 - Double click the chosen process, or select the process and click Attach button.

From this moment on, the running app has been attached to the debugger and you could be able to debug it using Visual Studio as always. 

To pause the execution, you must set a breakpoint. You can do that in two ways:
- insert a breakpoint in a function. You must enter the name of the function (you must know its name).
- open the project and set a breakpoint.

To stop debugging, you have three options:
- Menu Debug -> Stop debugging (or Stop Debugging button): Stop the debugging process and detach the debugger. The app continues running.
- Menu Debug -> Detach All: Stops all the processes that are being debugged, detaching the debugger.  The app continues running.
- Menu Debug -> Terminate All: Terminates both the debugging session and the app.

**Comment by zadmarbella** [comment]
Attach to process Blackberry Transport is not available on build 1.01.0013

**Comment by zadmarbella** [comment]
#199 this issue blocks the testing of this feature

**Comment by zadmarbella** [comment]
10.2.0.435 build on a q5 and 10 looks to attach.

**Comment by zadmarbella** [comment]
verified on build 123 ver 1.0.1.0018 Simulator/Device 10.2.0.435 
tests created and filed issues
