### ISSUE TITLE
b123 - attach to process looks to hang when ip is incorrect

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#248]
build 123 ver 1.0.1.0018 Q5 10.2.0.435
Prerequisite: Device/Simulator with incorrect IP Blackberry VS Plugin Settings
1. Debug > Attach To Process
2. Select Transport Blackberry
3. Select Qualifier Device: <IP Address>

Current Behaviour:
VS stops responding for a while and VS looks to hang

Expected:
prompted message that plugin is unable to connect to device

**Comment by mattcostanzo** [comment]
.5 day

**Comment by guarnold** [comment]
When the IP is incorrect: it hangs for 3 or 4 seconds because GDB tries to connect to that IP. After that time, a message box is presented, indicating that the IP is incorrect.

When there is no device connected: it hangs for 7 to 8 seconds, then it presents a message box advertising the user that VS is attempting to connect to a device. The user can decide if he wants to continue (yes) or abort (no). If he decides to continue, he might have to wait up to 40 more seconds if the device keeps disconnected. But if he connects the device and click "yes", the list of running processes is presented. If he takes more than 50 seconds to connect or to click "yes", another message is presented informing him that the connection failed.

**Comment by guarnold** [comment]
Now, if the device is not connected, it hangs for 7 to 8 seconds, then it presents a message box advertising the user that VS is attempting to connect to a device. However, the user cannot decide if he wants to continue. The only option is to interrupt the current task. The user can restart the task if he wants.

**Comment by zadmarbella** [comment]
verified on 1.01.0026
user is able to view warning notification but notification might need to be reworded #360 
user is still able to notice that the attach to process dialog stops responding before the notification message #360
