### ISSUE TITLE
Avoid the Security Alert when opening the internal browser for the new signing feature.

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#274]
Related to issue #265.

**Comment by zadmarbella** [comment]
unclear on how to verify the issue.
Looks to happen when launching for signing the first time 
the user is asked to download a certificate (looks to be twice)
before they are able to proceed to creating their bbid tokens.

**Comment by allee** [comment]
Dave to clarify

**Comment by srinivas4912** [comment]
I followed below steps to verify:
1. Open Visual Studio 2013.
2. From BlackBerry > signing > Register.
3. Open "Sign in to create and download your BlackBerry ID token" dialog.
4. Input Username, Password fields and Sign In.
Actual Result: no security alert is shown and user is able to create BB ID token
![11](https://f.cloud.github.com/assets/5992406/2159032/bc208414-949d-11e3-94d6-0315fc9937f0.png)

Found that issue is fixed.
