### ISSUE TITLE
[1.01.0025] unable to create bar-descriptor file in vs2012

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#349]
1. Create Visual C++ Empty Project
2. From Project Contexual Menu Add > New Item
3. From the Add New Item Window Select BlackBerry and BlackBerry OS Application Descriptor
4. Click Add

Current Behaviour:
Error Invalid at the top level of the document dialog occurs and no bar-descriptor file appears in project when dialog is closed.

**Comment by guarnold** [comment]
This message happens when user tries to add a bar-descriptor file in a non BlackBerry project.

We must decide about the possibility of adding bar-descriptor manually, because all of the bar-descriptor files are created automatically for every BlackBerry app. Even if the bar-descriptor file is deleted, another one is created automatically. Also, it doesn't make sense adding bar-descriptor files in non BlackBerry projects.

**Comment by guarnold** [comment]
#378 - "It was decided to remove the blackberry add item menu item as it is redundant. The bar-descriptor is added automatically when the BlackBerry configuration is added."

We can close this issue as soon as task #378 is complete.
