### ISSUE TITLE
[1.01.0033] project continues to deploy on devices with valid debug tokens when the vsplugin has none setup

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#430]
preq: have device installed with a debug token from the machine and debug a project on the device.
1. remove signing keys from BlackBerry > Signing > Click Unregister
2. Attempt to debug again

Current Behaviour:
Notification appears no signing keys registered.
And the project continues to deploy.

This is probably an edge case.
Not really clear if this is expected behaviour should be.

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by pvallabhaneni** [comment]
Verified the issue using 2.0.0022 plugin on win7 64 bit and found as fixed in the following scenario.
1.  Installed plugin and registered the signing keys.
2.  Deployed debug tokens on to the device.
3.  debugged the project on the device.
4.  removed signing keys from BlackBerry > Signing > Click Unregister
5.  attempt to debug again.

Error message appeared as follows and project is not deployed to the device.
![untitled](https://f.cloud.github.com/assets/5992422/2157568/e8c6ea5e-947e-11e3-8cc3-8c1cb2b83ace.png)
