### ISSUE TITLE
[1.01.0042] adding images and splash page to project sometimes builds them without those assets 

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#457]
vs2010 added icon and splash images to gameplay project and thumnails do not appear
vs2012 removed and added icons and splash images to fallingblocks project and images do not appear when launching on device.

Note: the issue looks to be reproducible, unclear what causes it.

Linking #414

**Comment by dbrgss** [comment]
Did you add the images to the assets listing??   They need to be added there as well...  If you want the thumbnail to appear they need to be added there first.

**Comment by dbrgss** [comment]
I can't reproduce this issue on my environment.  I will need to come look at your scenario.

**Comment by zadmarbella** [comment]
[1.01.0043] we are seeing behaviour where previous app information persists on device. ie. Application Name.

Possible workaround could be resetting the device and trying again.

**Comment by guarnold** [comment]
The fix for issue #480 might have solved this one at the same time. Before this fix, the icon/splash screen had to be located under the project directory. If it was located somewhere else, it was not being found by the bar-descriptor editor. That might be the cause why the project was being built without those assets.
Please, verify if this issue is still reproducible.

**Comment by srinivas4912** [comment]
It is verified and found as fixed using VS2012/13 plugin from build 2.0.0018 on Win8.1 and Win7 64 bit.
