### ISSUE TITLE
[1.01.0045] trying to access debug token window doesn't have a progress indicator when a background process is happening

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#487]
This is more apparent with incorrect information is inputted in the Settings Window
1. input incorrect device information in the Blackberry > Settings
2. Access the Debug token Window Blackberry > Debug

Current behaviour: 
the environment becomes unresponsive as a connection is attempted

Expected behaviour:
some sort of process indicator.

Workaround:
right now is to just wait until it is completed.

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by guarnold** [comment]
Using VS 2013, it normally takes 3 seconds to retrieve the debug token information using the correct settings and, during that time, the environment is unresponsive.

With Incorrect password -> it takes 2 seconds
With Incorrect IP -> it takes 2 seconds
With Device disconnected -> it takes 10 seconds

There is no way to present any message while trying to retrieve the debug token information because no data is received. But we can change the cursor. At least, it will show that it is processing something.

**Comment by guarnold** [comment]
Now, the cursor changes while processing the debug token dialog.

**Comment by srinivas4912** [comment]
Passed verification using VS2013/12 plugin from v2.0.0022 on Win8.1/Win7 64 bit and found as fixed.
