### ISSUE TITLE
[2.0.0001] debugging on older OS runtime always prompts download if newer OS runtime is installed

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#501]
preq: have 2 devices one with a 10.2.1791 and one 10.2.1725
1. launch to debug on 10.2.1791, downloads the runtime and launches successfully.
2. do the same for the 10.2.1725 device.

Current behaviour
On vs2010 is that it attempts to download and errors out and the user gets spammed with Java errors and proceeds to launch. 
In VS2012 it doesn’t have the java errors 

No runtime folder exists bbndk_vs folder

Attempting to debug again on the 10.2.1725 device prompts the runtime download again.

**Comment by dbrgss** [comment]
Estimate: 0.5 Days

**Comment by guarnold** [comment]
If the runtime folder is not created, it means that the runtime is not available externally, i.e., it is not possible to download it. That also means that you are running an OS version that is available only internally. As a consequence, VS will always prompt the runtime download.

**Comment by guarnold** [comment]
Verified with OS versions 1791 and 1725. Both runtime folders were created.
Verify if you can see the information about the used runtime in the build log.

**Comment by pvallabhaneni** [comment]
Verified on Win 7 64 bit with a device having 10.2.0.1791 OS and downloaded the corresponding runtimes to download. Then connected a device containing 10.2.0.1725 OS and tried to debug. Then  Visual Studio prompted to download the 10.2.0.1725 runtime.

**Comment by guarnold** [comment]
If the 10.2.0.1725 runtime is not installed, it is the expected behavior. You must download and install the 1725 runtime to be able to debug a project.

However, if you have already downloaded and installed the 10.2.0.1725 runtime and it asks to download it again, it means that your bbndk_vs folder is probably corrupt. There is a task to investigate what is causing this issue (#594).

To verify if the folder is corrupt, you have to run the runtime installer manually. If the folder is not created after installing it manually, it is because the folder is corrupt and you have to delete the qconfig and bbndk_vs folders to be able to fix it.

Please, verify if the 10.2.0.1725 runtime is installed in the bbndk_vs folder. If it is not, this is the correct behavior.

**Comment by pvallabhaneni** [comment]
Application is working as per the above comments.
