### ISSUE TITLE
"Deploy" option is not present in Win 7 32bit using VS2012 (Bundle 187)

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#566]
Install VS2012 & NDK plugin(Bundle 187) on Win7 (32bit) system.
Open a project.
Build the project.
Right click on the project.

Actual Result: "Deploy" menu is not present in the context menu.
Expected Result: "Deploy" menu should be present in the list of context menu.

Note: This menu is visible in Win7 - 64 bit system with the same NDK plugin.

**Comment by pvallabhaneni** [comment]
This bug is reproduced intermitently.

**Comment by guarnold** [comment]
Could not reproduce this issue in Win 7 64 bits, using VS2012, as described above.
Tried with bundle 187 and 191. Could you try it with bundle 191? Or wait till the next build is available?

As I could read, you have installed the VS2012 and the NDK. I would like to know if you have created the BlackBerry and BlackBerrySimulator platform configurations, as we have to do after installing  VS. Maybe the deploy option is not presented because there is no BlackBerry configuration. Could you verify that?

**Comment by guarnold** [comment]
Could not reproduce this issue in a Win 7 32 bits environment, using VS2012 and bundle 187. The Deploy option is available in the menu when you right click on the project.

Please, try to verify this issue using a different project. Maybe, the used project might be corrupt.

**Comment by pvallabhaneni** [comment]
I tried with different projects on Win 8.1 and Win 7 64 bit using 2.0.0018 version of plugin, 10.2.1.1925 runtime, 10.2 API level and found as working fine.
