### ISSUE TITLE
[2.0.0012]Able to download author.p12 without logging in BBID and entering any (wrong) BBID Token password.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#569]
Steps to reproduce: 
Scenario 1:
1. Install VS2012 and NDK plugin Bundle 187 on Win7 (32bit or 64bit).
2. Go to Blackberry->Signing->Click Register.
3. "Sign in to create and download your BlackBerry ID Token" dialog opens.
4. Close the dialog without entering the login credentials.
5. Registration Window dialog opens.
6. Enter Author name and wrong BB Id Token Password and click OK.

Actual result: author.p12 is being download without any error.
Expected Result: Error should be shown that wrong password is entered  and author.p12 should not be downloaded.

Scenario 2: 
1. Install VS2012 and NDK plugin Bundle 187 on Win7 (32bit or 64bit).
2. Go to Blackberry->Sigining->Clieck Register.
3. "Sign in to create and download your BlackBerry ID Token" dialog opens.
4. Enter valid credentials and download .csk file,
5. Registration Window dialog opens.
6. Enter Author name and wrong BB Id Token Password and click OK.

Actual result: author.p12 is being download without any error.
Expected Result: Error should be shown that wrong password is entered and author.p12 should not be downloaded.

**Comment by guarnold** [comment]
Fixed for scenario 1. If user closes the browser without downloading the bbidtoken.csk file, the registration window will not open and, as a consequence, the author.p12 will not be created.

About the scenario 2: it works as expected. That happens because it is not possible to verify the password in this step. We can only verify it when creating the debug token. If the user entered the wrong password during the registration, he will not be able to create the debug token. He will get the error message and the registration window will open again. At this moment the user has two options: 1 - Proceed with the registration, if he remember the correct password; 2 - Close this registration window and start the signing process again, downloading a new bbidtoken.csk file and then proceeding to registration (at this moment he must know the right password, because he has just downloaded the csk file). In both cases, the debug token window will be closed automatically. The user must open it again to be able to create the debug token.

**Comment by guarnold** [comment]
Available in the next build

**Comment by pvallabhaneni** [comment]
Verified in Win 7 - 32bit using VSNDK Plugin Bundle 193[2.0.0016] and found scenario 1 as fixed.

Now user is unable to register without entering the login credentials and logging in. Also author.p12 is not downloaded if sign in dialog is closed.
