### ISSUE TITLE
[2.0.0001] able to verify correct runtime is used

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#574]
VS2012 
Win8.1
Steps:
1 Using #538 workaround download a 10.2.1 runtime
2 Attempt to debug
3 Review the gdb logs

Current behaviour:
seeing runtime path appear 
Path to is logged: C:\bbndk_vs\runtime_10_2_1_1055
When on path exists.

Sample log:
16:25:21 - 6set solib-search-path C:\bbndk_vs\runtime_10_2_1_1055\qnx6\armle-v7\lib;C:\bbndk_vs\runtime_10_2_1_1055\qnx6\armle-v7\usr\lib;C:\bbndk_vs\runtime_10_2_1_1055\qnx6\armle-v7\usr\lib\qt4

16:25:21 - &"set solib-search-path C:\bbndk_vs\runtime_10_2_1_1055\qnx6\armle-v7\\lib;C:\bbndk_vs\runtime_10_2_1_1055\qnx6\armle-v7\\usr\lib;C:\bbndk_vs\runtime_10_2_1_1055\qnx6\armle-v7\\usr\lib\qt4\n"

16:25:21 - 6^done

**Comment by zadmarbella** [comment]
seeing the same behaviour using [2.0.0014] on win8.1 vs2013
using 10.2.1.1925
log:
11:14:40 - 6set solib-search-path C:\bbndk_vs\runtime_10_2_1_1844\qnx6\armle-v7\lib;C:\bbndk_vs\runtime_10_2_1_1844\qnx6\armle-v7\usr\lib;C:\bbndk_vs\runtime_10_2_1_1844\qnx6\armle-v7\usr\lib\qt4

**Comment by guarnold** [comment]
I was able to reproduce this issue when my bbndk_vs folder was corrupted. After deleting this folder, as well as the qconfig one, this issue was not reproducible anymore.

I was able to verify that the path to the used runtime exists.

I have two questions/comments:
1 - would it be good to have the used runtime and api level information available in the output window?
2 - need to verify if this issue is reproducible when the environment is not corrupt.
3 - need to verify what makes the environment corrupt. Maybe after cancelling the api level/runtime installation (see issue #450)?

**Comment by guarnold** [comment]
When the environment is not corrupt, this issue is reproducible only when using internal runtimes/api levels that are not available externally. In such a situation, the gdb-output.log file may present that a specific runtime is being used while the respective folder does not exist. It is also possible to debug the app, but it won't be able to locate the shared libraries with symbols if needed. To avoid this issue, manually download the respective runtime using the tool pointing to an internal server.

So, there is nothing to change in the source code to solve this issue because the plug-in searches for runtimes/api levels only at the servers available externally. 

The workaround for compatibility tests is to download manualy the respective runtime.

Another issue is being created to investigate what might be causing the bbndk-vs folder to be corrupt.

**Comment by srinivas4912** [comment]
It is verified using VS2013/VS2012 plugin from build 2.0.0018 on Win8.1 and Win7 (64&32) bit and found as fixed
