### ISSUE TITLE
[2.0.00.16] Removed bar-descriptor.xml file is created again

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#611]
Preq: Install VS2012 on Win 32bit NDK plugin.

Steps to Reproduce:
1.Create a C++ empty project.
2.Create a Blackberry build configuration from Configuration Manager.
3.Observe that bar-descriptor.xml file is created.
4.Right click on the bar-descriptor.xml file and select "Remove"
5.Prompt occurs to remove or delete or cancel.
6.Click "Remove"

Actual Result: Observe that the bar-descriptor file is removed and added again to the project. Go to the folder in which bar-descriptor file is present. Observe that the bar-descriptor is deleted and created once again (Time stamp changed).

Expected Result: bar-descriptor.xml file should be deleted and created once again only if deleted but not when removed.

**Comment by guarnold** [comment]
This is the expected behavior. A BlackBerry application must have a bar-descriptor file. That/s why a new one is automatically created when you delete the old one.

The delete/remove options have the same behavior for the bar-descriptor file, that is, to delete the existing one and to create a new one automatically.

If you do not want to have a new bar-descriptor file created, you have to change the configuration platform to anything else than BlackBerry or BlackBerrySimulator.
