### ISSUE TITLE
[2.0.0018] If don't have API level for device OS, It's prompting for runtime libraries instead of API level for device OS

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#617]
Preq: 1. Install VS2013 plug-in from Bundle 195[2.0.0018] on Win7 64bit and using Naples R085 with 10.2.1.1925 build OS.
2. Have API level 10.2.0.1155 but don't have API level for device OS, project to debug

Steps to reproduce:
1. debug project 

Actual Result:
It is prompting to install Runtime Libraries for the device OS

Expected Result:
It should prompt to install API level, if does not exist.

**Comment by guarnold** [comment]
The behavior is correct.

API levels are required to download for all of the OS versions 10.0 and 10.1.

Since 10.2, we are using runtimes, so it is correct to ask for the runtime if you have a 10.2.0.1155 API level installed. It should ask for 10.2 API level download only if you don't have the 10.2.0.1155 installed.

**Comment by srinivas4912** [comment]
It is not an issue for 10.2 OS version.
