### ISSUE TITLE
[2.0.0018] Unable to stop debugging when power off the simulator/device

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#623]
Preq: 1. Install VS2013 plug-in from Bundle 195[2.0.0018] on Win7 64bit using 10.2.1.1925 and 10.2.0.1155 simulators

Steps to reproduce:
1. Debug a project on a simulator
2. hit a breakpoint 
3. Power off the simulator 

Actual Result:
Project debug session is not stopped.

**Comment by guarnold** [comment]
This issue is reproducible in the device too.

If the user tries to continue debugging, VS will keep waiting for a response from the simulator/device. To stop debugging, the user has to hit the stop button.

It was expected to close the debug session when the user tries to debug an app in a device/simulator that was powered off.

**Comment by hkopparru** [comment]
tested with [3.0.0005] VS 2013 and the issue is reproducible, Unable to stop debugging when power off the device.

**Comment by dbrgss** [comment]
Related to #621
