### ISSUE TITLE
[2.0.0022] "break when the hit count is multiple of" is not working correctly.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#648]
Preq:
Win OS: Win 7 64 bit
VS Version: VS2012

Steps to Reproduce:
1. Set a break-point that breaks "when the hit count is multiple of".
2. Debug the project.

Actual Result: Observe that debugging is breaking even though the hit count condition is not satisfied.
![bug](https://f.cloud.github.com/assets/5992422/2206710/5be0ee8a-9967-11e3-8fe4-b695593892fa.png)

In Win 32, Observed that the debugging is break only when the hit count satisfies the condition.

**Comment by guarnold** [comment]
Please, have a look at the gdb-output.log file and verify how many times that breakpoint was hit (search for breakpoint-modified and look at the value in "times".). 

Also, create a counter variable (int count = 0;) and add an instruction that increments its value by 1 before the breakpoint, and verify if the value of this variable is 1 or 3 when the breakpoint is hit. 

I believe that the "current hit count" is showing the number of times that the execution stopped in a given breakpoint (that should be 1), instead of presenting the correct hit count number (that should be 3).

**Comment by guarnold** [comment]
I am unable to reproduce this issue using VS 2013 and 2012.

To verify the hit counts, just open the breakpoints window: Debug -> Windows -> Breakpoints

Please, verify it again. If this issue is still reproducible, create a counter variable (int count = 0;) and add an instruction that increments its value by 1 before the breakpoint. Then, verify if the value of this variable is 1 or 3 when the breakpoint is hit.

Also, send us the gdb-output.log file by email, in case this issue is still reproducible. Do not forget to include the API level and the OS version.

**Comment by pvallabhaneni** [comment]
Verified on a fresh machine and found as working fine. Functionality is similar to that of in Win 32 project debugging.
