### ISSUE TITLE
[2.0.0022] "break when hit count is greater than or equal to" is nor working correctly.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#649]
Preq: 
Win OS: Win 7 64 bit
VS version : VS2012

Steps to Reproduce:
1. Set a break-point with hit count condition set to "break when the hit count is greater then or equal to " and give some value.
2. debug the project.

Actual Result: Observe that the debugging is halt even if the break-point condition for hit count is not met.
![111111](https://f.cloud.github.com/assets/5992422/2206786/fb3f7ad6-9968-11e3-99ae-9cf15d5e76f2.png)

**Comment by dbrgss** [comment]
Does this behavior reproduce for all of the conditions??  Or just the greater than or equal to.

**Comment by pvallabhaneni** [comment]
It is not working for "greater than or equal to" and for "when hit count is multiple of". the condition when hit count is equal to" is working fine.

**Comment by guarnold** [comment]
Please, have a look at the gdb-output.log file and verify how many times that breakpoint was hit (search for breakpoint-modified and look at the value in "times".). 

Also, create a counter variable (int count = 0;) and add an instruction that increments its value by 1 before the breakpoint, and verify if the value of this variable is 1 or 3 when the breakpoint is hit. 

I believe that the "current hit count" is showing the number of times that the execution stopped in a given breakpoint (that should be 1), instead of presenting the correct hit count number (that should be 3).

**Comment by guarnold** [comment]
I am unable to reproduce this issue using VS 2013 and 2012.

To verify the hit counts, just open the breakpoints window: Debug -> Windows -> Breakpoints

Please, verify it again. If this issue is still reproducible, create a counter variable (int count = 0;) and add an instruction that increments its value by 1 before the breakpoint. Then, verify if the value of this variable is 1 or 3 when the breakpoint is hit.

Also, send us the gdb-output.log file by email, in case this issue is still reproducible. Do not forget to include the API level and the OS version.

**Comment by pvallabhaneni** [comment]
Verified on a fresh machine and found as working fine. Functionality is similar to that of win 32 debugging. Not reproducing.
