### ISSUE TITLE
[2.0.0022] VS2013 - SDK installation is not finishing correctly !

### ISSUE THREAD

**Issue by MrKaktus** [blackberry/VSPlugin#657]
When opening VS2013 Solution first time after installing BB VS2013 Plugin, I see "API Levels" window popup that says:

Please choose your default API Level to be used by the Visual Studio Plug-in:
o BlackBerry Native SDK 10.0
o BlackBerry Native SDK 10.1
[Close][Install]

Selecting for e.g SDK 10.0 and clicking [Install] starts SDK installation process, that when finished, displays only text "Complete". Window is still visible, there is no "OK" button or any other acknowledgement button. [Install] is grayed out and the only two options are to [Close] or use red X window close. Also your selection in radio button is missing like if you didn't select anything.

Installing 10.0 or 10.1 from within the Visual Studio using BLACKBERRY > Settings > [Get More..] results in the same behavior. 

RESULT:
Even though I see new files downloaded to plugin directory (for 10.0 ir 10.1), this SDKs are displayed as "Available" and not "Installed" in "API Levels" window called from withing Visual Studio. I cannot choose any of this two SDK's in Settings dropdown menu as well.

REPRODUCTIVITY:
100%  on Visual Studio 2013 Ultimate and Windows 7 64bit SP1

**Comment by MrKaktus** [comment]
INVESTIGATION:
It looks that even though you cannot choose installation destination for plugin (and it always installs at: C:\bbndk_vs ), when you download given SDK level ( for e.g. 10.0 ) during starting of some solution, QCONFIG dir for this API level is created in root dir of the driver where given solution lays and not in the C:. As a results installed API's are not seen.

Example:
H:\Engine\engine.sln <- open solution , install 10.0 SDK
H:\qconfig <- new dir is now here
copy it to C:\
Now new configuration is available.
But still 10.2 configuration cannot be uninstalled.
I think something is seriously messed up in plugin and it interacts with Momentics settings.
Please fix this.

Also, why the hell I need to install Momentics IDE to just download NDK ????

**Comment by guarnold** [comment]
1 - About your last comment: Visual Studio Plug in is completely detached from Momentics IDE. So, you don't need to install Momentics to download NDK.

2 - What might be happening to you is that the bbndk_vs folder might be corrupted. There is an issue to investigate what is causing this problem (#594). Whenever you install an NDK but you cannot see it, that's because the folder is corrupt (it was not supposed to happen, that's why there is a separate investigation)

The only way to fix this folder problem for now is:
I - close Visual Studio;
II - delete the bbndk_vs and qconfig folders completely.

Then you can use VS normally (don't forget to install an NDK).

Please, let us know if this workaround solves this issue for you. 

Anyways, we are going to investigate the following issue and create another one related to it if needed: 

"It looks that even though you cannot choose installation destination for plugin (and it always installs at: C:\bbndk_vs ), when you download given SDK level ( for e.g. 10.0 ) during starting of some solution, QCONFIG dir for this API level is created in root dir of the driver where given solution lays and not in the C:. As a results installed API's are not seen.

Example:
H:\Engine\engine.sln <- open solution , install 10.0 SDK
H:\qconfig <- new dir is now here
copy it to C:\"

**Comment by hkopparru** [comment]
found this issue in [3.0.0001] VS 2013 Windows 7, when i try to install the 10.0 and 10.1 ndks then its started installation successfully but after some time the installation got stopped(nothing is currently executing)

**Comment by hkopparru** [comment]
tested this in [3.0.0015] VS 2013, where i am able to install successfully all API levels(10.0, 10.1, 10.2 and 10.3) and able to select the installed one successfully. so closing this issue now.
