### ISSUE TITLE
[3.0.0005] Unable to import Momentics  Core Native Project into Visual Studio.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#680]
Environment:
System OS: Win 7 64bit and Win 8.1
VS Plugin version: 3.0.0005

Prerequisite: A Blackberry Core Native Project
Steps to Reproduce:
1. From Visual Studio File > New > New Project...
2. From New Project Select New Visual C++ > Empty Project in a solution
3. Provide a relevant name
4. click OK
5. from project contextual menu right click
6. Import BlackBerry Core Native Project
7. Browse for .project or .cproject and click Ok
8. Review Conversion log for errors
9. Click Ok

Actual Result: An Error message is thrown as follows:

![bug](https://cloud.githubusercontent.com/assets/5992422/6039235/c7c53476-ac8a-11e4-8456-697a8995668e.png)

Expected Result: Import Summary successfully copies project assets into correct folders
.   Images to Resource Files
.   Source to Source Files
.   Header to Header Files

**Comment by phofman** [comment]
You must be doing something really really wrong ;) There is no option for step 6. I did removed it long time ago. Are you sure you don't have 2.0 and 3.0 versions in parallel?? Yes, it is possible as the plugin Guid has changed for VS2012 and VS2013. [Here](/phofman/vs-plugin/wiki/Port-Existing-Project) is the guide, how importing should look like and behave. For example - there is no summary screen and inside the Visual Studio navigate to File -> New -> Project... -> BlackBerry Projects -> Cascades... to create BlackBerry specific native project.

**Comment by dbrgss** [comment]
The error still occurs using the new import user flow.  The issue lies in our installation.  We are not copying the Templates folder into the C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\NDK Plugin folder.  This is required for import to work correctly.  (When I manually copied these files and reran the test all work correctly.  

To fix..  

Need to modify the build script to copy the Template folder into the buildresults folder.
Need to modify the installer to pick this folder up and install to the appropriate directory.

**Comment by dbrgss** [comment]
Please note.. the old user flow for importing projects is no longer valid.  You should NOT see the menu item listed in step 6 above.

**Comment by phofman** [comment]
One more hint: use the build script with the "package" param (ie.: "build.bat /package:3.0.5") and then install the vsix instead of any manual copying. This will also upgrade old version automatically, if you keep incrementing version strings in ConfigDefaults.cs and all .vsixmanifests.

**Comment by dbrgss** [comment]
Unfortunately I don't believe that will work.  We are no longer building for vs2010 or vs2012 and from what I see from the above command this builds for all three.   (I would have to modify anyways)  

It is weird though.. if I build with build vs2013 and then use the vsix to install.. I cannot find the files installed in there usual location.. IE 
.
C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\

Not sure if this normal or if I am doing something wrong.

**Comment by phofman** [comment]
That's correct, build script forces creation of all editions - I am using it to create public releases :) but the change is extremely simple.

About the vsix - that's also correct, the plugin's folder just receives a random name, managed by vsix installer, under 'Extensions'.

**Comment by dbrgss** [comment]
Unfortunately we cannot, at this time, utilize the vsix method for install.   Our InstallShield installer will have to do.  My question is.. is there anything else that needs to be done.. other than distributing the files into the right places. (Including the Template folder that I missed)  I think you removed the necessity of creating registry keys. (Awesome by the way) 

BTW: I did try installing via the vsix and I get a crash when I try to create a Native Core - Empty Project.  I get a message..  An argument was out its legal range. (Exception from HRESULT:0x80131502)

When I trace the code.. I can see that its failing in the following function.

```
    /// <summary>
    /// Init constructor.
    /// </summary>
    public ProjectFolderTree(Project project, bool createDefaultFolders)
    {
        if (project == null)
            throw new ArgumentNullException("project");

        _vcProject = project.Object as VCProject;
        if (_vcProject == null)
            throw new ArgumentOutOfRangeException("project", "This is not Visual C++ project");

        _projectFolder = Path.GetDirectoryName(_vcProject.ProjectFile) + Path.DirectorySeparatorChar;
        Refresh(createDefaultFolders);
    }
```

Its failing because _vcProject is coming back null...  

Not sure if you have seen that before.   I assume I have something not quite setup right.

**Comment by phofman** [comment]
In the past I used WiX, which installs VSIX packages out-of-the-box. I have no idea, how to make InstallShield to do it, but should be fairly simple according to [this short guide](http://blogs.msdn.com/b/visualstudio/archive/2009/10/27/vsix-and-msi.aspx). Unzip the VSIX package, recreate the same directory structure and all should work. Add extra field into .vsixmanifest file to prevent manual uninstallations from inside VS.

I think the Template folder is all you need. Remember it is built from two parts. One that is a set of 'shared' files, that are added into projects and the second part - the .vcproject files itself, that are solution-specific. It might also be nice, if you remove the 'Qt' folder from being released (and update the items.vsdir accordingly), so my 'experimental' project doesn't go public, although it doesn't do much.

Yes, I removed all the registry hacks and did components registration the right way ;) I used lots of custom [RegistrationAttribute](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.registrationattribute%28v=vs.110%29.aspx)s to populate settings, that are placed in .pkgdef. Nice thing about them is that they are placed into respective local hive only. That's why the features like debugger and my custom full-blown project-wizard work for VS2010, VS2012 and VS2013 at the same time. Otherwise you could have a DLL-hell and ID-hell, to keep different GUIDs for each edition for each component and each template descriptor... 

About your error - I did checked it on 3 machines with different configurations and no problem spot. Project is always created without single warning. Do you use VS2013 Update 4? Is the _project_ and _project.Object_ also _null_? What version of the VCEngine library is displayed, when you try to print typeof(VSProject).FullName? At the very beginning, when I started refactoring of VS2013 solution, I noticed that all hint paths to VS-specific libraries, were wrong and were mostly pointing to VS2012 or randomly into space. Maybe there is really something wrong with your installation then.

**Comment by dbrgss** [comment]
So I got this working.  Thanks for your help Pavel.  It turned out that the error I was receiving was due to a bad build environment on one of my machines.  Building on a different PC with a clean environment solved the issue.   Preparing to send this back for verification.

**Comment by pvallabhaneni** [comment]
[3.0.0015] Now I am able to import projects using the above steps.

While verifying the functionality in different scenarios, I have observed the following.

Steps to Reproduce:
1. Open VS 2013
2. Do not create or open any project.
3. Goto Blackberry->Import BlackBerry Core Native Project and select .cproject

![1](https://cloud.githubusercontent.com/assets/5992422/6125591/b6965862-b13d-11e4-94f0-3e86035e2858.PNG)
1. Import Momentics Project dialog appears. Click OK

![2](https://cloud.githubusercontent.com/assets/5992422/6125599/c8e5b346-b13d-11e4-9a50-68aa71e2d773.png)
1. Then Visual Studio asks to save the project

![3](https://cloud.githubusercontent.com/assets/5992422/6125606/d618b626-b13d-11e4-8058-998bae557115.PNG)
1. Click Cancel.

Actual Result: Observe that the project is being created but the files are not imported.

![4](https://cloud.githubusercontent.com/assets/5992422/6125612/ed2aa6c6-b13d-11e4-8654-aaea022bad44.PNG)

**Comment by phofman** [comment]
Nice catch ;)

Call to `_dte.Solution.SaveAs(path)` is responsible for displaying UI and can end-up with exception, when developer presses [Cancel] button. As a side-effect, this actually could skip the method adding files into imported VS project.

Fixed and made a part of #691 pull-request. More details in the commit reference above.

**Comment by pvallabhaneni** [comment]
Also observed the following using 3.0.00015 plugin.

When an empty project is created and then if a Momentics Project is imported, the project is imported as a new project.

![1](https://cloud.githubusercontent.com/assets/5992422/6127669/9643bd28-b153-11e4-90b3-d7e856e437cf.PNG)

![2](https://cloud.githubusercontent.com/assets/5992422/6127671/996fd950-b153-11e4-90e9-2985e35553e3.PNG)

Expected Result: Momentics Project contents has to be imported into empty project. But it should not be imported as another new project.

**Comment by phofman** [comment]
There is plenty of options on the 'confirmation dialog' displayed after choosing the Momentics Project.
Among them, there is a combo-box (next to the '_Destination_' label) describing, what should be done - i.e. created new project or added into existing one ;) It even suggests all projects from current solution.

Take a look on the image you already posted:
![Importing](https://cloud.githubusercontent.com/assets/5992422/6125599/c8e5b346-b13d-11e4-9a50-68aa71e2d773.png)

**Comment by dbrgss** [comment]
As a summary: Pawel... correct me if I am less then clear..  :-)  

The Desitination drop down allows the user to either import into a NEW project created at import time.. or to import into the currently selected project.

The 'copy source files' check box.. tells the import to copy the source files into the new project space.. over writting colliding files.

The 'Create at source project location' creates a new project at the location of the import source..  just adding the required files for making it a VS project.

The Defines, Libraries and Incl Dirs text boxes are settings gleaned from the .project .cproject file. and aid in the conversion.

**Comment by phofman** [comment]
That's all correct, plus:
- settings are also extracted from _manifest.properties_, if found
- _bar-descriptor.xml_ is updated, if 'cached publisher info' is available

**Comment by pvallabhaneni** [comment]
Verified the import functionality using 3.0.0017 plugin and found that error message is not thrown.
