### ISSUE TITLE
[3.0.0005] Able to add multiple targets with same IP address

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#683]
Environment:
System OS: Win 8.1 64-bit and Win 7 64-bit

Steps to Reproduce:
1) Go to BlackBerry > Options...
2) Select BlackBerry > Targets
3) Click on Add... Button, Add New Target Device dialog appears
4) Select the type as USB device and enter some password and click on OK
5) Repeat steps 3 and 4 

Actual Result:
It can add same IP address multiple times.
![image](https://cloud.githubusercontent.com/assets/5992406/6060003/0d3173fc-ad5e-11e4-967c-329a6b254d5d.png)

And also IP Address field accepting alphanumeric key values:
![image](https://cloud.githubusercontent.com/assets/5992406/6060197/9974224a-ad60-11e4-8e2e-aaf1adaa4492.png)

**Comment by phofman** [comment]
What in my opinion is a great feature, not a bug. I have personally 4 BB10 phones, each with different password. Dev can specify any name instead of 'USB' and quickly switch between owned devices.

Similar type of bug could be forbid adding the same variable into Watch Window, while debugging. But why? IMHO devs know, what they do.

The real bug could be instead, when you specify multiple devices with the same IP, that something stops to work at all, or that password from the first one is always used, no matter what set for selected one. However this doesn’t happen, correct me if I'm wrong :)

Voting for: invalid

**Comment by dbrgss** [comment]
I agree with Pavel on this.  I don't see this as being a bug.  The use case that he has stated is definitely valid.

**Comment by srinivas4912** [comment]
As per the comments, this isn't an issue and closing.
