### ISSUE TITLE
[3.0.0015] Author name is not modified at all instances when modified in Cached Publisher Summary

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#696]
Environment: 
System OS: Win 7 64bit and Win 8.1

Steps to Reproduce:
1. Complete signing registration
2. Goto Signing page in Option dialog
3. Click "Edit Publisher info..."
4. Edit the author name in "Cached Publisher Summary" dialog.
5. Click OK
6. Click "Load" button 

Actual result: Author name is not modified in "Developer Certificate to sign applications" section as in "Cached Publisher Summary" dialog when modified.
Expected Result: Author name has to be the same at all instances(Cached Publisher Summary dialog, Author name at Developer Certificate to sign application section in Signing page...)

**Comment by phofman** [comment]
I think your assumptions are wrong here. Or mines ;) Those values don't need to be identical all the time.

The Developer Certificate is something that was generated during the registration process and is placed in a X.509 certificate. It is used to sign the .bar files and is a foundation for all validation paths. That's why you need to place a reference to this certificate inside your bar-descriptor.xml (as author field) as well as developer-token links to this.

On top of that there is NO way of obtaining both values without a path to valid debug-token, so it's metadata can be read freely (through some QNX Java-tool). To read the developer-certificate you still need the password and there is even no author-id stored in ;) Or at least I have no idea, how to generate it on the client machine. 

And since I wanted to make first app creation and Momentics project importing as smooth as possible I came up with 'Cached Publisher Info'. Developer can put there ANY text and this text is simply placed inside the bar-descriptor.xml in author and author-id fields (instead of Example app.). It's not validated at all, it might be equal to values from developer-certificate/debug-token or not. In most cases it probably will as it is synchronized each time you open the debug-token (in Options->Targets->Upload debug-token... or on bar-descriptor editor).

At the time of adding this feature I was importing ALL BlackBerry samples from GitHub to create VS2013 projects for them. Without 'cached' values, if I would need to import author info from debug-token more than 100 times and I would have gone crazy by that ;)

So, should the changes in 'Cached Publisher info' by pushed down to the Developer Certificate?
NO! If you loose your certificate, you won't be recognized as the author of your old apps and won't be able to publish updates...

Proposal: ticket invalid/reject

**Comment by dbrgss** [comment]
I agree with Pavel on this one.. 

Working as designed

**Comment by pvallabhaneni** [comment]
Closing the issue as per the above comments.
