### ISSUE TITLE
[3.0.0015] User is able to overwrite signing keys but not the developer certificate.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#699]
Environment:
System OS: Win 7 64bit and Win 8.1

Steps to Reproduce:
1. Goto Blackberry->Options->Blackberry->signing Page
2. Click "Register..." button and open developer Registration dialog.
3. Enter Valid Author name, Password, Confirm Password and click "Create Token..." button.
4. Enter valid BBID and Password and download the csk file.
5. Click "Create Certificate..." button.
6. Observe that the certificate is created and status is shown as "Certificate creation finished"

Actual Results: Observe that the "Create Token" button is enabled and user is able to over-write the existing csk file, but user is unable to overwrite the developer certificate as "Create Certificate..." button is disabled.

![ct](https://cloud.githubusercontent.com/assets/5992422/6166373/8feac524-b2d5-11e4-8803-213d3e94c813.png)

**Comment by phofman** [comment]
Once you generated the developer certificate it is valid for next 30 years and links you with released applications. Since you generate it again, you won't be able to publish updates to your apps, instead you will need to remove them from AppWorld and publish again losing link/reviews/etc.

Why do you want to allow developer to create certificate again? If you 'Unregister' this button will become enabled again, what in my opinion avoids all accidential losses of the certificate. There is even a comment that registration has been completed.

On the other hand token let's you sign the apps. It's valid only for 1 year, what is relatively short. Beside that it can be regenerated as many times as needed without any negative impacts. That's why this button stays enabled all the time.

Voting for: reject/invalid ticket.

**Comment by dbrgss** [comment]
I agree with Pawel on this one..  CLosing
